# Generated by Django 5.1.4 on 2024-12-22 13:23

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(max_length=256)),
                ('Created_At', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=254)),
                ('Admin', models.BooleanField(db_default=False)),
                ('Email', models.CharField(max_length=254, unique=True)),
                ('Password', models.TextField()),
                ('Profile_Picture', models.BinaryField()),
                ('Created_At', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubCategory_Name', models.CharField(max_length=256)),
                ('Created_At', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.category')),
                ('Created_By', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.user')),
            ],
            options={
                'db_table': 'subcategories',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='Created_By',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.user'),
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('App_Name', models.CharField(max_length=254)),
                ('App_link', models.URLField()),
                ('Description', models.TextField()),
                ('Points', models.IntegerField()),
                ('Application_Picture', models.BinaryField()),
                ('Created_At', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('Screenshots', models.JSONField(default={})),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.category')),
                ('Subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.subcategory')),
                ('Created_By', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.user')),
            ],
            options={
                'db_table': 'applications',
            },
        ),
    ]
