# Generated by Django 5.1.4 on 2024-12-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Category_Name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
