# Generated by Django 5.1.4 on 2024-12-23 07:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_alter_applications_app_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='App_Name',
            field=models.CharField(blank=True, max_length=254, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='applications',
            name='App_link',
            field=models.URLField(blank=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
